pipeline{
  agent any
  
  stages{
    stage("Git Checkout"){
      steps{
        script{
          git branch: 'main', changelog: false, poll: false, url: 'https://github.com/balu1123/Python-Webapp.git'
        }
      }  
    }

    
  }
}