pipeline{
  agent any
  
  stages{
    stage("Git Checkout"){
      steps{
        script{
          git branch: 'main', changelog: false, poll: false, url: 'https://github.com/balu1123/Python-Webapp.git'
        }
      }  
    }

    stage("OWASP"){
      steps{
        script{
          dependencyCheck additionalArguments: '', odcInstallation: 'DP'
			    dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
        }
      }
    }

    stage("Sonar Analysis"){
      steps{
        script{
          withSonarQubeEnv(credentialsId: 'sonar')
        }
      }
    }
  }
}